Description of numrows
Home > . > numrows.m
numrows
PURPOSE
NUMROWS Return number of rows in matrix
SYNOPSIS
function r = numrows(m)
DESCRIPTION
NUMROWS Return number of rows in matrix
    NR = NUMROWS(M)
 Return the number of rows in the matrix M.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eul2r EUL2R Convert Euler angles to homogeneous transformation
eul2tr EUL2TR Convert Euler angles to homogeneous transformation
rne RNE Compute inverse dynamics via recursive Newton-Euler formulation
rpy2r RPY2TR Roll/pitch/yaw to homogenous transform
rpy2tr RPY2TR Roll/pitch/yaw to homogenous transform
SOURCE CODE
%NUMROWS Return number of rows in matrix
%
%    NR = NUMROWS(M)
%
% Return the number of rows in the matrix M.
% Copyright (C) 1993-2002, by Peter I. Corke
% $Log: numrows.m,v $
% Revision 1.2  2002-04-01 11:47:15  pic
% General cleanup of code: help comments, see also, copyright, remnant dh/dyn
% references, clarification of functions.
%
% $Revision: 1.2 $
function r = numrows(m)
    [r,x] = size(m);