Description of ospace
Home > . > ospace.m
ospace
PURPOSE
OSPACE Operational space coefficients
SYNOPSIS
This is a script file.
DESCRIPTION
OSPACE Operational space coefficients
 [Lambda, mu, p] = ospace(robot, q, qd)
CROSS-REFERENCE INFORMATION
This function calls:
coriolis CORIOLIS Compute the manipulator Coriolis matrix
gravload GRAVLOAD Compute the gravity loading on manipulator joints
inertia INERTIA Compute the manipulator inertia matrix
jacob0 JACOB0 Compute manipulator Jacobian in world coordinates
ospace OSPACE Operational space coefficients
This function is called by:
ospace OSPACE Operational space coefficients
SOURCE CODE
%OSPACE Operational space coefficients
%
% [Lambda, mu, p] = ospace(robot, q, qd)
%
[Lambda, mu, p] = ospace(robot, q, qd)
    M = inertia(robot, q);
    C = coriolis(robot, q);
    g = gravload(robot, q);
    J = jacob0(robot, q);
    Ji = inv(J);
    Lambda = Ji' * M * Ji;
    mu = J' * C - Lambda * H * qd;
    p = J' * g;