Description of rotx
Home > . > rotx.m
rotx
PURPOSE
ROTX Rotation about X axis
SYNOPSIS
function r = rotx(t)
DESCRIPTION
ROTX Rotation about X axis
    TR = ROTX(theta)
 Returns a homogeneous transformation representing a rotation of theta
 about the X axis.
 See also: ROTY, ROTZ, ROTVEC.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
rpy2r RPY2TR Roll/pitch/yaw to homogenous transform
rpy2tr RPY2TR Roll/pitch/yaw to homogenous transform
trotx ROTX Rotation about X axis
SOURCE CODE
%ROTX Rotation about X axis
%
%    TR = ROTX(theta)
%
% Returns a homogeneous transformation representing a rotation of theta
% about the X axis.
%
% See also: ROTY, ROTZ, ROTVEC.
% $Log: rotx.m,v $
% Revision 1.3  2007-01-21 06:30:46  cor134
% Generate rotation matrices as 3x3 matrices, not 4x4 as previously.  This
% might break a few things...
%
% Revision 1.2  2002/04/01 11:47:16  pic
% General cleanup of code: help comments, see also, copyright, remnant dh/dyn
% references, clarification of functions.
%
% $Revision: 1.3 $
% Copyright (C) 1993-2002, by Peter I. Corke
function r = rotx(t)
    ct = cos(t);
    st = sin(t);
    r =    [1    0    0
        0    ct    -st
        0    st    ct];