Description of roty
Home > . > roty.m
roty
PURPOSE
ROTY Rotation about Y axis
SYNOPSIS
function r = roty(t)
DESCRIPTION
ROTY Rotation about Y axis
    TR = ROTY(theta)
 Returns a homogeneous transformation representing a rotation of theta
 about the Y axis.
 See also: ROTX, ROTZ, ROTVEC.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eul2r EUL2R Convert Euler angles to homogeneous transformation
eul2tr EUL2TR Convert Euler angles to homogeneous transformation
rpy2r RPY2TR Roll/pitch/yaw to homogenous transform
rpy2tr RPY2TR Roll/pitch/yaw to homogenous transform
troty ROTY Rotation about Y axis
SOURCE CODE
%ROTY Rotation about Y axis
%
%    TR = ROTY(theta)
%
% Returns a homogeneous transformation representing a rotation of theta
% about the Y axis.
%
% See also: ROTX, ROTZ, ROTVEC.
% $Log: roty.m,v $
% Revision 1.3  2007-01-21 06:30:46  cor134
% Generate rotation matrices as 3x3 matrices, not 4x4 as previously.  This
% might break a few things...
%
% Revision 1.2  2002/04/01 11:47:16  pic
% General cleanup of code: help comments, see also, copyright, remnant dh/dyn
% references, clarification of functions.
%
% $Revision: 1.3 $
% Copyright (C) 1993-2002, by Peter I. Corke
function r = roty(t)
    ct = cos(t);
    st = sin(t);
    r =    [ct    0    st
        0    1    0
        -st    0    ct];