Description of rpy2tr
Home > . > rpy2tr.m
rpy2tr
PURPOSE
RPY2TR Roll/pitch/yaw to homogenous transform
SYNOPSIS
function T = rpy2tr(roll, pitch, yaw)
DESCRIPTION
RPY2TR Roll/pitch/yaw to homogenous transform
     TR = RPY2TR([R P Y])
    TR = RPY2TR(R,P,Y)
 Returns a homogeneous tranformation for the specified roll/pitch/yaw angles.
 These correspond to rotations about the Z, Y, X axes respectively.
 See also: TR2RPY, EUL2TR
CROSS-REFERENCE INFORMATION
This function calls:
numcols NUMCOLS Return number of columns in matrix
numrows NUMROWS Return number of rows in matrix
r2t R2T Return a homogeneous transformation from a rotation
rotx ROTX Rotation about X axis
roty ROTY Rotation about Y axis
rotz ROTZ Rotation about Z axis
This function is called by:
SOURCE CODE
%RPY2TR Roll/pitch/yaw to homogenous transform
%
%     TR = RPY2TR([R P Y])
%    TR = RPY2TR(R,P,Y)
%
% Returns a homogeneous tranformation for the specified roll/pitch/yaw angles.
% These correspond to rotations about the Z, Y, X axes respectively.
%
% See also: TR2RPY, EUL2TR
% $Log: rpy2tr.m,v $
% Revision 1.4  2007-01-21 06:33:53  cor134
% Allow operation on a matrix, each row is a triple of angles.  Result is a
% 4x4xN matrix of homog transforms.
%
% Revision 1.3  2002/04/14 11:00:30  pic
% Fixed error in axis rotation order.
%
% Revision 1.2  2002/04/01 11:47:16  pic
% General cleanup of code: help comments, see also, copyright, remnant dh/dyn
% references, clarification of functions.
%
% $Revision: 1.4 $
% Copyright (C) 1993-2002, by Peter I. Corke
function T = rpy2tr(roll, pitch, yaw)
    if (nargin == 1),
        if numcols(roll) ~= 3,
            error('bad arguments')
        end
        pitch = roll(:,2);
        yaw = roll(:,3);
        roll = roll(:,1);
    end
    if numrows(roll) == 1,
        r = rotz(roll) * roty(pitch) * rotx(yaw);
        T = r2t(r);
    else
        for i=1:numrows(roll),
            r = rotz(roll(i)) * roty(pitch(i)) * rotx(yaw(i));
            T(:,:,i) = r2t(r);
        end
    end