Description of skew
Home > . > skew.m
skew
PURPOSE
SYNOPSIS
function a = skew(b)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ishomog ISHOMOG Test if argument is a homogeneous transformation
isrot ISHOMOG Test if argument is a homogeneous transformation
isvec ISVEC Test if argument is a homogeneous transformation
This function is called by:
SOURCE CODE
function a = skew(b)
    if isrot(b),
        a = 0.5*[b(3,2)-b(2,3); b(1,3)-b(3,1); b(2,1)-b(1,2)];
    elseif ishomog(b),
        d = [    b(1:3,4);
            0.5*[b(3,2)-b(2,3); b(1,3)-b(3,1); b(2,1)-b(1,2)]];
    elseif isvec(b,3),
        a = [
        0    -b(3)    b(2)
        b(3)    0    -b(1)
        -b(2)    b(1)    0];
    elseif isvec(b,6),
        a = [
        0    -b(6)    b(5)    b(1)
        b(6)    0    -b(4)    b(2)
        -b(5)    b(4)    0    b(3)
        0    0    0    1];
    end