Description of double
Home > @quaternion > double.m
double
PURPOSE
DOUBLE Convert a quaternion object to a 4-element vector
SYNOPSIS
function v = double(q)
DESCRIPTION
DOUBLE Convert a quaternion object to a 4-element vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
minus MINUS Subtract two quaternion objects
mrdivide MRDIVIDE Compute quaternion quotient.
mtimes MTIMES Multiply two quaternion objects
norm NORM Compute the norm of a quaternion
plus PLUS Add two quaternion objects
qinterp QINTERP Interpolate rotations expressed by quaternion objects
subsref SUBSREF Reference methods on a QUATERNION object
SOURCE CODE
%DOUBLE Convert a quaternion object to a 4-element vector
% $Log: double.m,v $
% Revision 1.2  2002-04-01 12:06:47  pic
% General tidyup, help comments, copyright, see also, RCS keys.
%
% $Revision: 1.2 $
%
% Copyright (C) 1999-2002, by Peter I. Corke
function v = double(q)
    v = [q.s q.v];