Description of inv
Home > @quaternion > inv.m
inv
PURPOSE
INV Invert a unit-quaternion
SYNOPSIS
function qi = inv(q)
DESCRIPTION
INV Invert a unit-quaternion
    QI = inv(Q)
 Return the inverse of the unit-quaternion Q.
CROSS-REFERENCE INFORMATION
This function calls:
quaternion QUATERNION Constructor for quaternion objects
This function is called by:
mpower MPOWER Raise quaternion to integer power
mrdivide MRDIVIDE Compute quaternion quotient.
mtimes MTIMES Multiply two quaternion objects
SOURCE CODE
%INV Invert a unit-quaternion
%
%    QI = inv(Q)
%
% Return the inverse of the unit-quaternion Q.
%
% $Log: inv.m,v $
% Revision 1.2  2002-04-01 12:06:17  pic
% Removed unneccessary normalization.
%
% $Revision: 1.2 $
%
% Copyright (C) 1999-2002, by Peter I. Corke
function qi = inv(q)
    qi = quaternion([q.s -q.v]);