Description of norm
Home > @quaternion > norm.m
norm
PURPOSE
NORM Compute the norm of a quaternion
SYNOPSIS
function n = norm(q)
DESCRIPTION
NORM Compute the norm of a quaternion
    QN = norm(Q)
 Return a unit-quaternion corresponding to the quaternion Q.
CROSS-REFERENCE INFORMATION
This function calls:
double DOUBLE Convert a quaternion object to a 4-element vector
norm NORM Compute the norm of a quaternion
This function is called by:
norm NORM Compute the norm of a quaternion
quaternion QUATERNION Constructor for quaternion objects
unit UNIT Unitize a quaternion
SOURCE CODE
%NORM Compute the norm of a quaternion
%
%    QN = norm(Q)
%
% Return a unit-quaternion corresponding to the quaternion Q.
%
% $Log: norm.m,v $
% Revision 1.2  2002-04-01 12:06:47  pic
% General tidyup, help comments, copyright, see also, RCS keys.
%
% $Revision: 1.2 $
%
% Copyright (C) 1993-2002, by Peter I. Corke
function n = norm(q)
    n = norm(double(q));