Description of friction
Home > @robot > friction.m
friction
PURPOSE
FRICTION Compute friction torque for a ROBOT object
SYNOPSIS
function tau = friction(robot, qd)
DESCRIPTION
FRICTION Compute friction torque for a ROBOT object
    TAU = FRICTION(ROBOT, QD)
 Return the vector of joint friction torques for the specified
 ROBOT object with link velocities of QD.
 SEE ALSO: LINK/FRICTION
CROSS-REFERENCE INFORMATION
This function calls:
friction FRICTION Compute friction torque for a ROBOT object
This function is called by:
friction FRICTION Compute friction torque for a ROBOT object
rne_dh RNE_DH Compute inverse dynamics via recursive Newton-Euler formulation
rne_mdh RNE_MDH Compute inverse dynamics via recursive Newton-Euler formulation
SOURCE CODE
%FRICTION Compute friction torque for a ROBOT object
%
%    TAU = FRICTION(ROBOT, QD)
%
% Return the vector of joint friction torques for the specified
% ROBOT object with link velocities of QD.
%
% SEE ALSO: LINK/FRICTION
% MOD HISTORY
% $Log: friction.m,v $
% Revision 1.1  2002-04-14 10:18:56  pic
% Remove friction from all links of robot.
%
% $Revision: 1.1 $
% Copyright (C) 1999-2002, by Peter I. Corke
function  tau = friction(robot, qd)
    L = robot.link;
    for i=1:robot.n,
        tau(i) = friction(L{i}, qd(i));
    end