Description of mat
Home > test > mat.m
mat
PURPOSE
SYNOPSIS
function x = mat(y)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dynamics
trajectory Test trajectory primitives
transform utility
SOURCE CODE
function x = mat(y)
    x = y;